#$: << File.dirname(__FILE__)
#require 'tictactien/board'
#require 'tictactien/game'
#require 'tictactien/rails_game'
#require 'tictactien/console_game'
#require 'tictactien/ai'
#require 'tictactien/player'
#require 'tictactien/human_player'
#require 'tictactien/cpu_player'
#require 'tictactien/minimax'
#require 'tictactien/perfect_ai'
#require 'tictactien/random_ai'
#require 'tictactien/player_factory'
#require 'tictactien/game_state'

$: << File.dirname(__FILE__) + '/../lib/tictactien'
require 'board'
require 'game'
require 'rails_game'
require 'console_game'
require 'ai'
require 'player'
require 'human_player'
require 'cpu_player'
require 'minimax'
require 'perfect_ai'
require 'random_ai'
require 'player_factory'
require 'game_state'
require 'render'
                        

